---Do A Pull Req With The Code And I will Add It
--- Tabs : TDS Scripts , Scripts  , MM2 , Arsenal , Misc , Dahood, Funky Friday <-- you can add whatever you want to all
--- USE TO ADD A FEATURE https://github.com/shlexware/Orion/blob/main/Documentation.md
